# NB: the URLs in this file should match those in blacklight.yml
development:
  url: <%= ENV['SOLR_HOST'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8983)}/solr/hydra-development" %>
test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
production:
  url: <%= ENV['SOLR_HOST'] %>
